common files added
zeckode/zecko-commons-java-public pull request #1
Opened 2022-11-23 13:22 UTC by jai38

2022-11-30 12:00 UTC, akartik80 requested changes
Every file other than `.java` files is junk, please remove

2022-11-30 12:00 UTC, akartik80 commented on .idea/.gitignore
> +# Default ignored files
Everything under `./idea` should go in gitignore

2022-11-30 12:00 UTC, akartik80 commented on pom.xml
> +    <groupId>co.zecko.common.java</groupId>
```suggestion
    <groupId>co.zecko.common</groupId>
```

2022-11-30 12:00 UTC, akartik80 commented on pom.xml
> +    <artifactId>client</artifactId>
```suggestion
    <artifactId>public</artifactId>
```

2022-11-30 12:00 UTC, akartik80 commented on pom.xml
> +    <name>Zecko Common Java</name>
```suggestion
    <name>Zecko Common Java Public</name>
```

2022-11-30 12:00 UTC, akartik80 commented on target/apidocs/allclasses-index.html
> +<!DOCTYPE HTML>
Why so many HTML classes?

2022-11-30 12:00 UTC, akartik80 commented on src/main/java/co/zecko/common/java/pojo/Extensions.java
> +public class Extensions {
Where is this used?

2022-11-30 17:13 UTC, jai38 commented on src/main/java/co/zecko/common/java/pojo/Extensions.java
> +public class Extensions {
in ErrorEntry and ErrorEntry is used in BaseEntry

2022-11-30 17:13 UTC, jai38 commented on target/apidocs/allclasses-index.html
> +<!DOCTYPE HTML>
that has to be in .gitignore

2022-11-30 17:24 UTC, jai38 commented on .idea/.gitignore
> +# Default ignored files
done

2022-12-01 06:53 UTC, akartik80 requested changes

2022-12-01 06:53 UTC, akartik80 commented on src/main/java/co/zecko/common/java/pojo/ErrorEntry.java
> +    Extensions extensions;
We don't need to show the cost to the client. This can be removed

2022-12-02 09:59 UTC, akartik80 approved these changes

2022-12-02 09:59 UTC, akartik80 commented on src/main/java/co/zecko/commonPublic/java/pojo/BaseDataBaseEntry.java
> +    private String createdBy;
private is default and not required. You can change in next PR

2022-12-02 09:59 UTC, merged